import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { 
  FileText, 
  Award, 
  Loader2, 
  Globe, 
  Download, 
  FileDown, 
  Printer, 
  ChevronDown, 
  ChevronUp, 
  ExternalLink,
  BarChart3,
  MessageSquare,
  PlaySquare
} from 'lucide-react';
import VisualCharts from './VisualCharts';
import ChatWithReport from './ChatWithReport';
import VoiceBriefing from './VoiceBriefing';
import PresentationModal from './PresentationModal';

export default function ReportViewer({ 
  query = '',
  draftReport, 
  finalReport, 
  researchResults = [], 
  isRunning, 
  activeAgent,
  provider = 'groq',
  model = '',
  apiKey = ''
}) {
  const [activeTab, setActiveTab] = useState('report');
  const [expandedSources, setExpandedSources] = useState({});
  const [isPresentationOpen, setIsPresentationOpen] = useState(false);

  const report = finalReport || draftReport;

  const toggleSource = (index) => {
    setExpandedSources(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const getStepClass = (stepAgent) => {
    const AGENT_ORDER = ['Coordinator', 'Researcher', 'Writer', 'Fact-Checker', 'Critic'];
    const activeIndex = AGENT_ORDER.indexOf(activeAgent);
    const stepIndex = AGENT_ORDER.indexOf(stepAgent);
    
    if (activeAgent === 'Finalize') return 'completed';
    if (activeAgent === 'Error') return 'error';
    if (activeIndex === -1) return 'pending';
    
    if (stepIndex < activeIndex) return 'completed';
    if (stepIndex === activeIndex) return 'active';
    return 'pending';
  };

  // Export as Markdown File (.md)
  const exportMarkdown = () => {
    if (!report) return;
    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `research_report_${new Date().toISOString().slice(0, 10)}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Export as static styled HTML Page (.html)
  const exportHTML = () => {
    if (!report) return;
    const titleMatch = report.match(/^#\s+(.*)$/m);
    const title = titleMatch ? titleMatch[1] : 'Research Report';
    
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body {
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.65;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
      color: #0f172a;
      background-color: #f8fafc;
    }
    h1, h2, h3, h4 {
      color: #0f172a;
      font-weight: 700;
      margin-top: 2em;
      margin-bottom: 0.5em;
      line-height: 1.25;
    }
    h1 {
      font-size: 2.25em;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 0.3em;
      margin-top: 0;
    }
    h2 {
      font-size: 1.5em;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 0.3em;
    }
    h3 { font-size: 1.25em; }
    p { margin-bottom: 1.25em; color: #334155; }
    ul, ol { margin-bottom: 1.25em; padding-left: 1.5em; color: #334155; }
    li { margin-bottom: 0.5em; }
    code {
      font-family: monospace;
      background-color: #e2e8f0;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 0.9em;
    }
    pre {
      background-color: #0f172a;
      color: #f8fafc;
      padding: 16px;
      border-radius: 8px;
      overflow-x: auto;
      font-family: monospace;
    }
    pre code {
      background-color: transparent;
      color: inherit;
      padding: 0;
    }
    blockquote {
      border-left: 4px solid #bd5cff;
      margin: 1.5em 0;
      padding-left: 1.5em;
      color: #475569;
      font-style: italic;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 2em 0;
    }
    th, td {
      border: 1px solid #cbd5e1;
      padding: 10px 12px;
      text-align: left;
    }
    th {
      background-color: #f1f5f9;
      font-weight: 600;
    }
    tr:nth-child(even) {
      background-color: #f8fafc;
    }
    a {
      color: #7c3aed;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
    .footer {
      margin-top: 4em;
      border-top: 1px solid #e2e8f0;
      padding-top: 2em;
      font-size: 0.875em;
      color: #64748b;
      text-align: center;
    }
  </style>
</head>
<body>
  <div id="content"></div>
  <div class="footer">
    Generated by Multi-Agent Autonomous Research Lab
  </div>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script>
    const markdownText = \`${report.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;
    document.getElementById('content').innerHTML = marked.parse(markdownText);
  </script>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `research_report_${new Date().toISOString().slice(0, 10)}.html`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Export as PDF (using system printer styled layout)
  const exportPDF = () => {
    if (!report) return;
    const titleMatch = report.match(/^#\s+(.*)$/m);
    const title = titleMatch ? titleMatch[1] : 'Research Report';
    const printWindow = window.open('', '_blank');
    
    printWindow.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            body {
              font-family: system-ui, -apple-system, sans-serif;
              line-height: 1.6;
              padding: 40px;
              color: #333;
              background: #fff;
            }
            h1, h2, h3 { color: #111; margin-top: 1.5em; }
            h1 { font-size: 2.2em; border-bottom: 2px solid #ccc; padding-bottom: 5px; }
            h2 { font-size: 1.6em; border-bottom: 1px solid #eee; padding-bottom: 3px; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f4f4f4; }
            pre { background: #f4f4f4; padding: 12px; border-radius: 6px; overflow-x: auto; font-family: monospace; }
            blockquote { border-left: 4px solid #7c3aed; padding-left: 15px; color: #555; font-style: italic; }
            a { color: #7c3aed; text-decoration: none; }
            .footer { margin-top: 50px; font-size: 0.8em; text-align: center; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
          </style>
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
        </head>
        <body>
          <div id="content"></div>
          <div class="footer">Generated by Multi-Agent Autonomous Research Lab</div>
          <script>
            const markdownText = \`${report.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;
            document.getElementById('content').innerHTML = marked.parse(markdownText);
            window.onload = function() {
              setTimeout(() => {
                window.print();
                window.close();
              }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="glass-panel report-panel">
      {/* Tabbed Navigation Header */}
      <div className="panel-title" style={{ justifyContent: 'space-between', padding: '10px 20px', alignItems: 'center' }}>
        <div className="tab-group">
          <button 
            type="button"
            className={`tab-btn ${activeTab === 'report' ? 'active' : ''}`}
            onClick={() => setActiveTab('report')}
          >
            <FileText size={13} />
            <span>Document</span>
          </button>
          <button 
            type="button"
            className={`tab-btn ${activeTab === 'charts' ? 'active' : ''}`}
            onClick={() => setActiveTab('charts')}
          >
            <BarChart3 size={13} />
            <span>Visual Charts</span>
          </button>
          <button 
            type="button"
            className={`tab-btn ${activeTab === 'chat' ? 'active' : ''}`}
            onClick={() => setActiveTab('chat')}
          >
            <MessageSquare size={13} />
            <span>Ask AI</span>
          </button>
          <button 
            type="button"
            className={`tab-btn ${activeTab === 'sources' ? 'active' : ''}`}
            onClick={() => setActiveTab('sources')}
          >
            <Globe size={13} />
            <span>Sources</span>
            {researchResults.length > 0 && (
              <span className="tab-badge">{researchResults.length}</span>
            )}
          </button>
        </div>

        {/* Verification Status & Export Actions */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          {finalReport && (
            <div style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '4px', 
              color: 'var(--accent-green)', 
              fontSize: '0.72rem',
              fontWeight: 600,
              background: 'rgba(16, 185, 129, 0.08)',
              padding: '2px 8px',
              borderRadius: '12px',
              border: '1px solid rgba(16, 185, 129, 0.2)',
              textTransform: 'uppercase',
              letterSpacing: '0.5px'
            }}>
              <Award size={12} /> Verified
            </div>
          )}

          {report && activeTab === 'report' && (
            <div className="export-group">
              <button 
                onClick={() => setIsPresentationOpen(true)} 
                className="export-action-btn present-action-btn" 
                title="Launch Fullscreen Presentation Deck (Slides)"
              >
                <PlaySquare size={13} style={{ color: 'var(--accent-purple)' }} />
                <span>Deck</span>
              </button>
              <button onClick={exportMarkdown} className="export-action-btn" title="Download Markdown (.md)">
                <Download size={13} />
                <span>MD</span>
              </button>
              <button onClick={exportHTML} className="export-action-btn" title="Download HTML (.html)">
                <FileDown size={13} />
                <span>HTML</span>
              </button>
              <button onClick={exportPDF} className="export-action-btn" title="Print / Save PDF">
                <Printer size={13} />
                <span>PDF</span>
              </button>
            </div>
          )}
        </div>
      </div>

      <div className="report-content">
        {activeTab === 'report' && (
          !report ? (
            isRunning ? (
              <div className="agent-loading-container">
                <div className="radar-container">
                  <div className="radar-circle circle-1"></div>
                  <div className="radar-circle circle-2"></div>
                  <div className="radar-circle circle-3"></div>
                  <div className="radar-core">
                    <Loader2 size={16} className="spinning-core" />
                  </div>
                  <div className="radar-pulse"></div>
                </div>

                <div className="loading-status-title">
                  <h3>Collaborating agents are researching...</h3>
                  <p className="active-agent-desc">
                    Active Agent: <span className="active-agent-badge">{activeAgent}</span>
                  </p>
                </div>

                <div className="agent-steps">
                  <div className={`agent-step ${getStepClass('Coordinator')}`}>
                    <div className="step-bullet">
                      {getStepClass('Coordinator') === 'completed' ? '✓' : '1'}
                    </div>
                    <div className="step-info">
                      <div className="step-name">Coordinator</div>
                      <div className="step-desc">Analyzing request and drafting research plan</div>
                    </div>
                  </div>

                  <div className={`agent-step ${getStepClass('Researcher')}`}>
                    <div className="step-bullet">
                      {getStepClass('Researcher') === 'completed' ? '✓' : '2'}
                    </div>
                    <div className="step-info">
                      <div className="step-name">Researcher</div>
                      <div className="step-desc">Scraping web indices and compiling raw facts</div>
                    </div>
                  </div>

                  <div className={`agent-step ${getStepClass('Writer')}`}>
                    <div className="step-bullet">
                      {getStepClass('Writer') === 'completed' ? '✓' : '3'}
                    </div>
                    <div className="step-info">
                      <div className="step-name">Writer</div>
                      <div className="step-desc">Assembling initial comprehensive report draft</div>
                    </div>
                  </div>

                  <div className={`agent-step ${getStepClass('Fact-Checker')}`}>
                    <div className="step-bullet">
                      {getStepClass('Fact-Checker') === 'completed' ? '✓' : '4'}
                    </div>
                    <div className="step-info">
                      <div className="step-name">Fact-Checker</div>
                      <div className="step-desc">Cross-checking benchmarks and correcting errors</div>
                    </div>
                  </div>

                  <div className={`agent-step ${getStepClass('Critic')}`}>
                    <div className="step-bullet">
                      {getStepClass('Critic') === 'completed' ? '✓' : '5'}
                    </div>
                    <div className="step-info">
                      <div className="step-name">Critic</div>
                      <div className="step-desc">Verifying editor quality and layout structure</div>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="report-placeholder">
                <FileText size={40} />
                <p>No report generated yet.<br/>
                <span style={{ fontSize: '0.8rem' }}>Enter a query and run research to trigger the agents.</span>
                </p>
              </div>
            )
          ) : (
            <div className="markdown-body">
              <VoiceBriefing report={report} />
              <ReactMarkdown>{report}</ReactMarkdown>
            </div>
          )
        )}

        {activeTab === 'charts' && (
          <VisualCharts report={report} />
        )}

        {activeTab === 'chat' && (
          <ChatWithReport 
            query={query} 
            report={report} 
            sources={researchResults} 
            provider={provider} 
            model={model} 
            apiKey={apiKey} 
          />
        )}

        {activeTab === 'sources' && (
          researchResults.length === 0 ? (
            <div className="report-placeholder">
              <Globe size={40} />
              <p>No research sources compiled yet.<br/>
              <span style={{ fontSize: '0.8rem' }}>Sources will appear here once the Researcher agent has gathered web intelligence.</span>
              </p>
            </div>
          ) : (
            <div className="sources-list">
              {researchResults.map((src, idx) => {
                let domain = '';
                try {
                  domain = new URL(src.url).hostname;
                } catch {
                  domain = src.url || 'web-source';
                }
                const isExpanded = !!expandedSources[idx];

                return (
                  <div key={idx} className="source-card">
                    <div className="source-card-header" onClick={() => toggleSource(idx)}>
                      <div className="source-card-meta">
                        <div className="source-favicon-box">
                          {domain !== 'web-source' ? (
                            <img 
                              src={`https://www.google.com/s2/favicons?domain=${domain}&sz=32`} 
                              alt="" 
                              className="source-favicon"
                              onError={(e) => {
                                e.target.style.display = 'none';
                                e.target.nextSibling.style.display = 'flex';
                              }}
                            />
                          ) : null}
                          <Globe size={14} className="source-favicon-fallback" />
                        </div>
                        <div className="source-title-box">
                          <a 
                            href={src.url} 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="source-title-link"
                            onClick={(e) => e.stopPropagation()}
                          >
                            {src.title || 'Untitled Reference'}
                            <ExternalLink size={11} className="inline-icon" />
                          </a>
                          <span className="source-domain-tag">{domain}</span>
                        </div>
                      </div>
                      
                      <span className="source-expand-icon">
                        {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                      </span>
                    </div>

                    {isExpanded && (
                      <div className="source-card-body">
                        <div className="source-body-section">
                          <span className="section-label">Extracted Snippet</span>
                          <p className="section-text">{src.snippet}</p>
                        </div>
                        {src.content && src.content !== src.snippet && (
                          <div className="source-body-section">
                            <span className="section-label">Full Scraped Content (Sample)</span>
                            <pre className="source-full-content-pre">{src.content}</pre>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )
        )}
      </div>

      {/* Fullscreen Interactive Presentation Deck Modal */}
      <PresentationModal
        isOpen={isPresentationOpen}
        onClose={() => setIsPresentationOpen(false)}
        report={report}
        query={query}
      />
    </div>
  );
}
