/**
 * Normalizes and repairs markdown formatting, specifically resolving collapsed
 * markdown tables, escaped newlines, and inline table rows generated by LLMs.
 */
export function normalizeMarkdown(text) {
  if (!text) return '';

  let cleaned = text;

  // 1. Convert literal escaped \n or \r\n if present
  if (cleaned.includes('\\n') && !cleaned.includes('\n\n')) {
    cleaned = cleaned.replace(/\\r\\n/g, '\n').replace(/\\n/g, '\n');
  }

  // 2. Remove <think> tags if any remain
  cleaned = cleaned.replace(/<think>[\s\S]*?<\/think>/gi, '');

  // 3. Fix collapsed markdown tables where rows are placed on the same line
  // e.g., "| Header 1 | Header 2 | | --- | --- | | Row 1 | Row 2 |"
  // or "| Header 1 | Header 2 ||---|---|| Row 1 | Row 2 |"
  cleaned = cleaned.replace(/\|\s*\|\s*/g, '|\n| ');

  // Fix separator rows directly attached to content
  // e.g. "| Col 1 | Col 2 | |--|--| | Val 1 | Val 2 |"
  cleaned = cleaned.replace(/\|\s*(\|[-:\s|]+\|)\s*\|/g, '|\n$1\n|');

  // Fix markdown headers glued to previous paragraphs: "end of text ## Header"
  cleaned = cleaned.replace(/([^\n])\s*(#{1,6}\s+[^\n]+)/g, '$1\n\n$2');

  // Ensure tables have a blank line before and after
  cleaned = cleaned.replace(/([^\n])\n(\|[^\n]+\|)/g, '$1\n\n$2');
  cleaned = cleaned.replace(/(\|[^\n]+\|)\n([^\n|#])/g, '$1\n\n$2');

  return cleaned;
}
